JavaScript语言执行环境是单线程的，单线程在程序执行时，所走的程序路径按照连续顺序排下来，前面的必须处理好，后面的才会执行。

但是我们也需要类似多线程机制的这种执行方式。但是JavaScript还是单线程的，我们需要异步执行，异步执行会使得多个任务并发执行。

多线程的任务可以[[8｜并行]]执行，而JavaScript单线程异步编程可以实现多任务[[7｜并发]]执行

JavaScript异步编程使得多个任务可以[[7｜并发]]执行，而实现这一功能的基础是JavaScript拥有一个基于事件循环的并发模型。

JavaScript引擎负责解析，执行JavaScript代码，但它并不能单独运行，通常都得有一个宿主环境，一般如浏览器或Node服务器，单线程是指在这些宿主环境创建单一线程，提供一种机制，调用JavaScript引擎完成多个JavaScript代码块的调度，执行（JavaScript代码都是按块执行的），这种机制就称为[[5｜事件循环]]（Event Loop）。

JavaScript代码执行就是在完成任务，所谓任务就是一个函数或一个代码块，通常以功能或目的划分，比如完成一次加法计算，完成一次ajax请求。

很自然的就分为同步任务和异步任务。同步任务是连续的，阻塞的；而异步任务则是不连续，非阻塞的，包含异步事件及其 #回调 ，当我们谈及执行异步任务时，通常指执行其 #回调 函数。

　　介绍JavaScript并发模型之前，了解[[ 2｜Js 堆栈和队列]]，了解[[12｜消息队列]]和[[11｜执行栈]]

事件循环流程使用代码可以描述如下：


```
   vareventLoop = [];

　　var event;

　　var i = eventLoop.length - 1; // 后进先出

　　while(eventLoop[i]) {

　　event = eventLoop[i--];

　　if (event) { // 事件回调存在

　　event();

　　}

　　// 否则事件消息被丢弃

　　}
```
　　这里注意的一点是等待下一个事件消息的过程是同步的。

　　并发模型与事件循环
```
　　varele = document.querySelector('body');

　　function clickCb(event) {

　　console.log('clicked');

　　}

　　function bindEvent(callback) {

　　ele.addEventListener('click', callback);

　　}

　　bindEvent(clickCb);
 ```

　当执行栈同步代码块依次执行完直到遇见异步任务时，异步任务进入等待状态，通知线程，异步事件触发时，往消息队列插入一条事件消息；而当执行栈后续同步代码执行完后，读取消息队列，得到一条消息，然后将该消息对应的异步任务入栈，执行回调函数；一次事件循环就完成了，也即处理了一个异步任务。

　　JS 中异步有几种？

　　JS中异步操作还挺多的，常见的分以下几种：

　　setTimeout(setInterval)

　　AJAX

　　Promise

　　Generator

　　setTimeout

　　setTimeout(

　　function() {

　　console.log("Hello!");

　　},1000);

　　setTimout（setInterval）并不是立即就执行的，这段代码意思是，等1s后，把这个function 加入任务队列中，如果任务队列中没有其他任务了，就执行输出'Hello'。

　　```
    varouterScopeVar;

　　helloCatAsync();

　　alert(outerScopeVar);

　　functionhelloCatAsync() {

　　setTimeout(function() {

　　outerScopeVar = 'hello';

　　}, 2000);

　　}
```

　　执行上面代码，发现outerScopeVar 输出是undefined，而不是hello。之所以这样是因为在异步代码中返回的一个值是不可能给同步流程中使用的，因为console.log(outerScopeVar) 是同步代码，执行完后才会执行setTimout。
```
　　helloCatAsync(function(result){

　　console.log(result);

　　});

　　functionhelloCatAsync(callback) {

　　setTimeout(

　　function() {

　　callback('hello')

　　}

　　, 1000)

　　}
  ```

　　把上面代码改成，传递一个callback，console输出就会是hello。

　　AJAX

```
　　varxhr = new XMLHttpRequest();

　　xhr.onreadystatechange= function() {

　　if ((xhr.status >= 200 && xhr.status < 300) ||xhr.status == 304 ) {

　　console.log(xhr.responseText);

　　} else {

　　console.log( xhr.status);

　　}

　　}

xhr.open('GET','url', false);

　　xhr.send();
  ```

　　上面这段代码，xhr.open中第三个参数默认为false 异步执行，改为true 时为同步执行。

　　Promise规范简述

　　promise是一个拥有then 方法的对象或函数。一个promise有三种状态pending, rejected, resolved状态一旦确定就不能改变，且只能够由pending状态变成rejected或者resolved状态，reject和resolved状态不能相互转换。

　　当promise执行成功时，调用then方法的第一个回调函数，失败时调用第二个回调函数。promise实例会有一个then方法，这个then方法必须返回一个新的promise。

　　基本用法
  ```

　　//异步操作放在Promise构造器中

　　constpromise1 = new Promise((resolve) => {

　　setTimeout(() => {

　　resolve('hello');

　　}, 1000);

　　});

　　//得到异步结果之后的操作

　　promise1.then(value=> {

　　console.log(value, 'world');

　　},error =>{

　　console.log(error, 'unhappy')

　　});
  ```

　　异步代码，同步写法

　　asyncFun()

　　.then(cb)

　　.then(cb)

　　.then(cb)

　　promise以这种链式写法，解决了回调函数处理多重异步嵌套带来的回调地狱问题，使代码更加利于阅读，当然本质还是使用回调函数。

　　异常捕获

　　前面说过如果在异步的callback函数中也有一个异常，那么是捕获不到的，原因就是回调函数是异步执行的。我们看看promise是怎么解决这个问题的。

```
　　asyncFun(1).then(function(value) {

　　throw new Error('出错啦');

　　},function (value) {

　　console.error(value);

　　}).then(function(value) {

　　},function (result) {

　　console.log('有错误',result);

　　});
  
 ```

　　其实是promise的then方法中，已经自动帮我们trycatch了这个回调函数，实现大致如下：

```
　　Promise.prototype.then= function(cb) {

　　try{

　　cb()

　　}catch (e) {

　　// todo

　　reject(e)

　　}

　　}
```
　　then方法中抛出的异常会被下一个级联的then方法的第二个参数捕获到（前提是有），那么如果最后一个then中也有异常怎么办。
```
　　Promise.prototype.done= function (resolve, reject) {

　　this.then(resolve, reject).catch(function (reason) {

　　setTimeout(() => {

　　throw reason;

　　}, 0);

　　});

　　};

　　asyncFun(1).then(function (value) {

　　throw new Error('then resolve回调出错啦');

　　}).catch(function (error) {

　　console.error(error);

　　throw new Error('catch回调出错啦');

　　}).done((reslove, reject) => {});
```
　　我们可以加一个done方法，这个方法并不会返回promise对象，所以在此之后并不能级联，done方法最后会把异常抛到全局，这样就可以被全局的异常处理函数捕获或者中断线程。这也是promise的一种最佳实践策略，当然这个done方法并没有被ES6实现，所以我们在不适用第三方Promise开源库的情况下就只能自己来实现了。为什么需要这个done方法。
```
　　constasyncFun = function (value) {

　　return new Promise(function (resolve, reject) {

　　setTimeout(function () {

　　resolve(value);

　　}, 0);

　　})

　　};

　　asyncFun(1).then(function(value) {

　　throw new Error('then resolve回调出错啦');

　　});
```
　　(node:6312)UnhandledPromiseRejectionWarning: Unhandled promise rejection(rejection id: 1): Error: then resolve回调出错啦

　　(node:6312)[DEP0018] DeprecationWarning: Unhandled promise rejections aredeprecated. In the future, promise rejections that are not handledwill terminate the Node.js process with a non-zero exit code

　　我们可以看到JavaScript线程只是报了一个警告，并没有中止线程，如果是一个严重错误如果不及时中止线程，可能会造成损失。

　　局限

　　promise有一个局限就是不能够中止promise链，例如当promise链中某一个环节出现错误之后，已经没有了继续往下执行的必要性，但是promise并没有提供原生的取消的方式，我们可以看到即使在前面已经抛出异常，但是promise链并不会停止。虽然我们可以利用返回一个处于pending状态的promise来中止promise链。
```
　　constpromise1 = new Promise((resolve) => {

　　setTimeout(() => {

　　resolve('hello');

　　}, 1000);

　　});

　　promise1.then((value)=> {

　　throw new Error('出错啦!');

　　}).then(value=> {

　　console.log(value);

　　},error=> {

　　console.log(error.message);

　　return result;

　　}).then(function() {

　　console.log('DJL箫氏');

　　});
```
　　特殊场景

　　当我们的一个任务依赖于多个异步任务，那么我们可以使用Promise.all，当我们的任务依赖于多个异步任务中的任意一个，至于是谁无所谓，Promise.race

　　上面所说的都是ES6的promise实现，实际上功能是比较少，而且还有一些不足的，所以还有很多开源promise的实现库，像q.js等等，它们提供了更多的语法糖，也有了更多的适应场景。

　　核心代码
```
　　vardefer = function () {

　　var pending = [], value;

　　return {

　　resolve: function (_value) {

　　value = _value;

　　for (var i = 0, ii = pending.length; i < ii; i++) {

　　var callback = pending[i];

　　callback(value);

　　}

　　pending = undefined;

　　},

　　then: function (callback) {

　　if (pending) {

　　pending.push(callback);

　　} else {

　　callback(value);

　　}

　　}

　　}

　　};
```
　　当调用then的时候，把所有的回调函数存在一个队列中，当调用resolve方法后，依次将队列中的回调函数取出来执行
```
　　varref = function (value) {

　　if (value && typeof value.then === "function")

　　return value;

　　return {

　　then: function (callback) {

　　return ref(callback(value));

　　}

　　};

　　};
```
　　这一段代码实现的级联的功能，采用了递归。如果传递的是一个promise那么就会直接返回这个promise，但是如果传递的是一个值，那么会将这个值包装成一个promise。

　　下面promise 和ajax 结合例子：
```
　　functionajax(url) {

　　return new Promise(function(resolve, reject) {

　　var xhr = new XMLHttpRequest();

　　xhr.onreadystatechange = function() {

　　if ((xhr.status >= 200 && xhr.status < 300) ||xhr.status == 304 ) {

　　resovle(xhr.responseText);

　　} else {

　　reject( xhr.status);

　　}

　　}

xhr.open('GET', url, false);

　　xhr.send();

　　});

　　}

　　ajax('/test.json')

　　.then(function(data){

　　console.log(data);

　　})

　　.cacth(function(err){

　　console.log(err);

　　});
```
　　generator

　　基本用法
```
　　function* gen (x) {

　　const y = yield x + 2;

　　// console.log(y); // 猜猜会打印出什么值

　　}

　　constg = gen(1);

　　console.log('first',g.next()); //first { value: 3, done: false }

　　console.log('second',g.next()); // second { value: undefined, done: true }
```
　　通俗的理解一下就是yield关键字会交出函数的执行权，next方法会交回执行权，yield会把generator中yield后面的执行结果，带到函数外面，而next方法会把外面的数据返回给generator中yield左边的变量。这样就实现了数据的双向流动。

　　generator实现异步编程

　　我们来看generator如何是如何来实现一个异步编程（*）
```
　　constfs = require('fs');

　　function* gen() {

　　try {

　　const file = yield fs.readFile;

　　console.log(file.toString());

　　} catch(e) {

　　console.log('捕获到异常',e);

　　}

　　}

　　//执行器

　　constg = gen();

g.next().value('./config1.json',function (error, value) {

　　if(error) {

　　g.throw('文件不存在');

　　}

g.next(value);

　　});
```
　　那么我们next中的参数就会是上一个yield函数的返回结果，可以看到在generator函数中的代码感觉是同步的，但是要想执行这个看似同步的代码，过程却很复杂，也就是流程管理很复杂。

　　[[异步编程与多线程的区别]]


　　